backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "index-page"}
          - {label: Heading, name: heading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
          - {label: "Quick Links", name: quickLinks, widget: object, fields: [
              {label: Title, name: title, widget: string}, 
              {label: Description, name: text, widget: text},
              {label: "Page Link", name: link, widget: string},
              {label: "PDF Link Text", name: docLinkText, widget: string},
              {label: "PDF Link", name: docLink, widget: string}
            ]}
      - file: "src/pages/our-company/index.md"
        label: "Our Company"
        name: "company"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "company-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Our Company"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/capabilities/index.md"
        label: "Capabilities"
        name: "capabilities"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "display-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Capabilities"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/services/index.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "display-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Services"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products"
        name: "products"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "display-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Products"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Contact Us"
        name: "contact"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "contact-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Contact"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: "Phone Number", name: "phoneNum1", widget: "string"}
          - {label: "Additional Phone Number", name: "phoneNum2", widget: "string"}
          - {label: "Fax Number", name: "faxNum", widget: "string"}
          - {label: "E-mail Address", name: "email", widget: "string"}
          - {label: "Office Days", name: "officeDays", widget: "string"}
          - {label: "Office Hours", name: "officeHours", widget: "string"}
          - {label: "Address Line 1", name: "addressLine1", widget: "string"}
          - {label: "Address Line 2", name: "addressLine2", widget: "string"}
          - {label: "Directions", name: "directions", widget: "text"}
