backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/uploads
public_folder: /uploads
display_url: https://fergusonbox.com
logo_url: src/img/ferguson_box_logo.png

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    editor:
          preview: false
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "index-page"}
          - {label: Heading, name: heading, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
          - {label: "Quick Link 1: Title", name: title1, widget: string}
          - {label: "Quick Link 1: Description", name: text1, widget: text}

          - {label: "Quick Link 2: Title", name: title2, widget: string}
          - {label: "Quick Link 2: Description", name: text2, widget: text}
          - {label: "Quick Link 2: PDF Link Text", name: docLinkText2, widget: string}

          - {label: "Quick Link 3: Title", name: title3, widget: string}
          - {label: "Quick Link 3: Description", name: text3, widget: text}
          - {label: "Quick Link 3: PDF Link Text", name: docLinkText3, widget: string}
      - file: "src/pages/our-company/index.md"
        label: "Our Company"
        name: "company"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "company-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Our Company"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Our Team Heading", name: "ourTeamHeading", widget: "string"}
          - {label: "Team", name: team, widget: list, fields: [
              {label: Photo, name: photo, widget: image}, 
              {label: Name, name: name, widget: string},
              {label: "Job Title", name: title, widget: string},
            ]}
      - file: "src/pages/capabilities/index.md"
        label: "Capabilities"
        name: "capabilities"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "display-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Capabilities"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/services/index.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "display-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Services"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products"
        name: "products"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "display-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Products"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/careers/index.md"
        label: "Careers"
        name: "careers"
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "display-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Careers"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Careers Link Label", name: "careersLinkLabel", widget: "string"}
          - {label: "Careers Link", name: "careersLink", widget: "string"}
      - file: "src/pages/contact/index.md"
        label: "Contact Us"
        name: "contact"
        editor:
          preview: false
        fields:
          - {label: "Template Key", name: templateKey, widget: hidden, default: "contact-page"}
          - {label: "Page Title", name: pageTitle, widget: hidden, default: "Contact"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: "Phone Number", name: "phoneNum1", widget: "string"}
          - {label: "Additional Phone Number", name: "phoneNum2", widget: "string"}
          - {label: "Fax Number", name: "faxNum", widget: "string"}
          - {label: "E-mail Address", name: "email", widget: "string"}
          - {label: "Office Days", name: "officeDays", widget: "string"}
          - {label: "Office Hours", name: "officeHours", widget: "string"}
          - {label: "Address Line 1", name: "addressLine1", widget: "string"}
          - {label: "Address Line 2", name: "addressLine2", widget: "string"}
          - {label: "Directions", name: "directions", widget: "text"}
